###
POST http://localhost:8080/FoodSpotsList
Content-Type: application/json

{
  "id": 2,
  "name": "CITY CHICKEN BERLIN",
  "category": "fast food",
  "address": "Sonnenallee 59, 12045 Berlin",
  "rating": 5 ,
  "website": "https://www.city-chicken-berlin.de/"
}
###
POST http://localhost:8080/FoodSpotsList
Content-Type: application/json

{
  "id": 3,
  "name": "Cocolo Ramen",
  "category": "Asiatische Küche (Ramen)",
  "address": "Paul-Lincke-Ufer 39-40, 10999 Berlin",
  "rating": 4.5,
  "website": "https://cocolo-ramen.com/"
}
###
POST http://localhost:8080/FoodSpotsList
Content-Type: application/json

{
  "id": 4,
  "name": "Borchardt",
  "category": "Französische Küche",
  "address": "Französische Straße 47, 10117 Berlin",
  "rating": 4,
  "website": "https://www.borchardt-restaurant.de/"
}
###
POST http://localhost:8080/FoodSpotsList
Content-Type: application/json

{
"id": 10,
"name": "Burger King",
"category": "Burger King Straße",
"address": "Französische Straße 47, 10117 Berlin",
"rating": 2,
"website": "https://www.burger-king.de/"
}